const products=[
{name:"EVANTINE TEE 001",meta:"Heavyweight cotton · $48",price:48,no:"01",type:"apparel",slug:"evantine-tee-001",description:"A substantial everyday tee designed as the starting point for Collection 001.",tilt:"7deg"},
{name:"STUDIO HOODIE 001",meta:"Brushed fleece · $96",price:96,no:"02",type:"apparel",slug:"studio-hoodie-001",description:"A soft, structured layer for cold walks, late nights, and everywhere between.",tilt:"-8deg"},
{name:"EVERYDAY CAP 001",meta:"Cotton twill · $38",price:38,no:"03",type:"objects",slug:"everyday-cap-001",description:"An understated everyday cap with an easy silhouette and studio attitude.",tilt:"12deg"},
{name:"EVANTINE TOTE 001",meta:"Heavy canvas · $42",price:42,no:"04",type:"objects",slug:"evantine-tote-001",description:"A durable carry-all for the things that follow you through the day.",tilt:"-6deg"}];
const $=s=>document.querySelector(s),grid=$("#productGrid"),resultCount=$("#resultCount"),bagCount=$("#bagCount"),toast=$("#toast"),menu=$(".menu-toggle"),nav=$("#site-nav"),bagPanel=$("#bagPanel"),bagItems=$("#bagItems"),bagTotal=$("#bagTotal"),bagButton=$(".bag-button"),bagClose=$("#bagClose"),overlay=$("#overlay"),modal=$("#productModal"),modalClose=$("#modalClose"),modalAdd=$("#modalAdd");
let bag=[];try{bag=JSON.parse(localStorage.getItem("evantineBag")||"[]");if(!Array.isArray(bag))bag=[];}catch{bag=[]}
let selected=null;
const money=n=>"$"+n.toFixed(2).replace(".00","");
function renderProducts(filter="all"){if(!grid)return;const visible=products.filter(p=>filter==="all"||p.type===filter);if(resultCount){resultCount.textContent=visible.length+" piece"+(visible.length===1?"":"s");resultCount.setAttribute("aria-label",visible.length+" pieces shown")}grid.innerHTML=visible.map(p=>'<article class="product-card" data-id="'+p.no+'"><a class="product-link" href="product.html?id='+p.no+'" aria-label="View '+p.name+'"><span class="product-image product-'+p.no+'"><span class="product-no">'+p.no+'</span><span class="product-type">'+p.type+'</span><span class="product-index">EV / 0'+p.no+'</span><span class="product-view">View piece ↗</span><span class="garment" aria-hidden="true"></span></span><span class="product-name">'+p.name+'</span><span class="product-meta">'+p.meta+'</span></a><button class="card-add" type="button" data-add="'+p.no+'" aria-label="Add '+p.name+' to bag">Add to bag</button></article>').join("");}
function updateBag(){if(!bagCount||!bagItems||!bagTotal)return;bagCount.textContent=bag.reduce((sum,item)=>sum+item.qty,0);const total=bag.reduce((sum,item)=>sum+item.price*item.qty,0);bagTotal.textContent=money(total);bagItems.innerHTML=bag.length?bag.map(item=>'<div class="bag-item"><span class="bag-thumb product-'+item.no+'"><span class="garment" aria-hidden="true"></span></span><div><h3>'+item.name+'</h3><p>'+item.qty+" × "+money(item.price)+'</p></div><button class="remove-item" type="button" data-remove="'+item.no+'" aria-label="Remove '+item.name+' from bag">Remove</button></div>').join(""):'<p class="empty-bag">Your bag is empty. Start with Collection 001.</p>';localStorage.setItem("evantineBag",JSON.stringify(bag));}
function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove("show"),2200);}
function closeOverlays(){if(bagPanel){bagPanel.classList.remove("open");bagPanel.setAttribute("aria-hidden","true");}if(bagButton)bagButton.setAttribute("aria-expanded","false");if(modal)modal.hidden=true;if(overlay)overlay.hidden=true;document.body.style.overflow="";if(bagButton)bagButton.focus();}
function openBag(){if(!bagPanel||!overlay)return;bagPanel.classList.add("open");bagPanel.setAttribute("aria-hidden","false");if(bagButton)bagButton.setAttribute("aria-expanded","true");overlay.hidden=false;document.body.style.overflow="hidden";if(bagClose)bagClose.focus();}
function openProduct(product){if(!modal)return;selected=product;$("#modalCategory").textContent=product.type+" / collection 001";$("#modalTitle").textContent=product.name;$("#modalMeta").textContent=product.meta;$("#modalDescription").textContent=product.description;modal.hidden=false;if(overlay)overlay.hidden=false;document.body.style.overflow="hidden";if(modalClose)modalClose.focus();}
function addToBag(product){const existing=bag.find(item=>item.no===product.no);if(existing)existing.qty++;else bag.push({...product,qty:1});updateBag();showToast(product.name+" added to bag");}
renderProducts();updateBag();
function setActiveNav(){const path=location.pathname.split("/").pop()||"index.html";document.querySelectorAll(".site-nav a").forEach(a=>{const href=a.getAttribute("href")||"";const target=href.split("#")[0].split("/").pop();if(target===path){a.setAttribute("aria-current","page")}else{a.removeAttribute("aria-current")}})}
setActiveNav();
document.querySelectorAll(".filter").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(b=>b.classList.remove("active"));button.classList.add("active");renderProducts(button.dataset.filter)}));
if(grid)grid.addEventListener("click",e=>{const add=e.target.closest("[data-add]");if(add){e.preventDefault();const product=products.find(p=>p.no===add.dataset.add);if(product)addToBag(product);}});
if(modalAdd)modalAdd.addEventListener("click",()=>{if(selected){addToBag(selected);closeOverlays();}});
if(bagItems)bagItems.addEventListener("click",e=>{const remove=e.target.closest("[data-remove]");if(!remove)return;bag=bag.filter(item=>item.no!==remove.dataset.remove);updateBag();});
if(bagButton)bagButton.addEventListener("click",openBag);if(bagClose)bagClose.addEventListener("click",closeOverlays);if(modalClose)modalClose.addEventListener("click",closeOverlays);if(overlay)overlay.addEventListener("click",closeOverlays);
if(menu)menu.addEventListener("click",()=>{const open=menu.getAttribute("aria-expanded")==="true";menu.setAttribute("aria-expanded",String(!open));if(nav)nav.classList.toggle("open",!open)});
if(nav)nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{if(menu)menu.setAttribute("aria-expanded","false");nav.classList.remove("open")}));
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeOverlays();});